<script setup>
import {ref} from "vue";

const emits = defineEmits(['update:modelValue'])
const props = defineProps([
    'modelValue',
    'country'
])
</script>

<template>
    <select @change="emits('update:modelValue', props.country || $event.target.value)" class="form-control"
            id="select">
        <option value="" disabled>Select country...</option>
        <option value="AX">AALAND ISLANDS</option>
        <option value="AF">AFGHANISTAN</option>
        <option value="AL">ALBANIA</option>
        <option value="DZ">ALGERIA</option>
        <option value="AS">AMERICAN SAMOA</option>
        <option value="AD">ANDORRA</option>
        <option value="AO">ANGOLA</option>
        <option value="AI">ANGUILLA</option>
        <option value="AQ">ANTARCTICA</option>
        <option value="AG">ANTIGUA AND BARBUDA</option>
        <option value="AR">ARGENTINA</option>
        <option value="AM">ARMENIA</option>
        <option value="AW">ARUBA</option>
        <option value="AU">AUSTRALIA</option>
        <option value="AT">AUSTRIA</option>
        <option value="AZ">AZERBAIJAN</option>
        <option value="BS">BAHAMAS</option>
        <option value="BH">BAHRAIN</option>
        <option value="BD">BANGLADESH</option>
        <option value="BB">BARBADOS</option>
        <option value="BY">BELARUS</option>
        <option value="BE">BELGIUM</option>
        <option value="BZ">BELIZE</option>
        <option value="BJ">BENIN</option>
        <option value="BM">BERMUDA</option>
        <option value="BT">BHUTAN</option>
        <option value="BO">BOLIVIA</option>
        <option value="BA">BOSNIA AND HERZEGOWINA</option>
        <option value="BW">BOTSWANA</option>
        <option value="BV">BOUVET ISLAND</option>
        <option value="BR">BRAZIL</option>
        <option value="IO">BRITISH INDIAN OCEAN TERRITORY</option>
        <option value="BN">BRUNEI DARUSSALAM</option>
        <option value="BG">BULGARIA</option>
        <option value="BF">BURKINA FASO</option>
        <option value="BI">BURUNDI</option>
        <option value="KH">CAMBODIA</option>
        <option value="CM">CAMEROON</option>
        <option value="CA">CANADA</option>
        <option value="CV">CAPE VERDE</option>
        <option value="KY">CAYMAN ISLANDS</option>
        <option value="CF">CENTRAL AFRICAN REPUBLIC</option>
        <option value="TD">CHAD</option>
        <option value="CL">CHILE</option>
        <option value="CN">CHINA</option>
        <option value="CX">CHRISTMAS ISLAND</option>
        <option value="CO">COLOMBIA</option>
        <option value="KM">COMOROS</option>
        <option value="CK">COOK ISLANDS</option>
        <option value="CR">COSTA RICA</option>
        <option value="CI">COTE D'IVOIRE</option>
        <option value="CU">CUBA</option>
        <option value="CY">CYPRUS</option>
        <option value="CZ">CZECH REPUBLIC</option>
        <option value="DK">DENMARK</option>
        <option value="DJ">DJIBOUTI</option>
        <option value="DM">DOMINICA</option>
        <option value="DO">DOMINICAN REPUBLIC</option>
        <option value="EC">ECUADOR</option>
        <option value="EG">EGYPT</option>
        <option value="SV">EL SALVADOR</option>
        <option value="GQ">EQUATORIAL GUINEA</option>
        <option value="ER">ERITREA</option>
        <option value="EE">ESTONIA</option>
        <option value="ET">ETHIOPIA</option>
        <option value="FO">FAROE ISLANDS</option>
        <option value="FJ">FIJI</option>
        <option value="FI">FINLAND</option>
        <option value="FR">FRANCE</option>
        <option value="GF">FRENCH GUIANA</option>
        <option value="PF">FRENCH POLYNESIA</option>
        <option value="TF">FRENCH SOUTHERN TERRITORIES</option>
        <option value="GA">GABON</option>
        <option value="GM">GAMBIA</option>
        <option value="GE">GEORGIA</option>
        <option value="DE">GERMANY</option>
        <option value="GH">GHANA</option>
        <option value="GI">GIBRALTAR</option>
        <option value="GR">GREECE</option>
        <option value="GL">GREENLAND</option>
        <option value="GD">GRENADA</option>
        <option value="GP">GUADELOUPE</option>
        <option value="GU">GUAM</option>
        <option value="GT">GUATEMALA</option>
        <option value="GN">GUINEA</option>
        <option value="GW">GUINEA-BISSAU</option>
        <option value="GY">GUYANA</option>
        <option value="HT">HAITI</option>
        <option value="HM">HEARD AND MC DONALD ISLANDS</option>
        <option value="HN">HONDURAS</option>
        <option value="HK">HONG KONG</option>
        <option value="HU">HUNGARY</option>
        <option value="IS">ICELAND</option>
        <option value="IN">INDIA</option>
        <option value="ID">INDONESIA</option>
        <option value="IQ">IRAQ</option>
        <option value="IE">IRELAND</option>
        <option value="IL">ISRAEL</option>
        <option value="IT">ITALY</option>
        <option value="JM">JAMAICA</option>
        <option value="JP">JAPAN</option>
        <option value="JO">JORDAN</option>
        <option value="KZ">KAZAKHSTAN</option>
        <option value="KE">KENYA</option>
        <option value="KI">KIRIBATI</option>
        <option value="KW">KUWAIT</option>
        <option value="KG">KYRGYZSTAN</option>
        <option value="LA">LAO PEOPLE'S DEMOCRATIC REPUBLIC</option>
        <option value="LV">LATVIA</option>
        <option value="LB">LEBANON</option>
        <option value="LS">LESOTHO</option>
        <option value="LR">LIBERIA</option>
        <option value="LY">LIBYAN ARAB JAMAHIRIYA</option>
        <option value="LI">LIECHTENSTEIN</option>
        <option value="LT">LITHUANIA</option>
        <option value="LU">LUXEMBOURG</option>
        <option value="MO">MACAU</option>
        <option value="MG">MADAGASCAR</option>
        <option value="MW">MALAWI</option>
        <option value="MY">MALAYSIA</option>
        <option value="MV">MALDIVES</option>
        <option value="ML">MALI</option>
        <option value="MT">MALTA</option>
        <option value="MH">MARSHALL ISLANDS</option>
        <option value="MQ">MARTINIQUE</option>
        <option value="MR">MAURITANIA</option>
        <option value="MU">MAURITIUS</option>
        <option value="YT">MAYOTTE</option>
        <option value="MX">MEXICO</option>
        <option value="MC">MONACO</option>
        <option value="MN">MONGOLIA</option>
        <option value="MS">MONTSERRAT</option>
        <option value="MA">MOROCCO</option>
        <option value="MZ">MOZAMBIQUE</option>
        <option value="MM">MYANMAR</option>
        <option value="NA">NAMIBIA</option>
        <option value="NR">NAURU</option>
        <option value="NP">NEPAL</option>
        <option value="NL">NETHERLANDS</option>
        <option value="AN">NETHERLANDS ANTILLES</option>
        <option value="NC">NEW CALEDONIA</option>
        <option value="NZ">NEW ZEALAND</option>
        <option value="NI">NICARAGUA</option>
        <option value="NE">NIGER</option>
        <option value="NG">NIGERIA</option>
        <option value="NU">NIUE</option>
        <option value="NF">NORFOLK ISLAND</option>
        <option value="MP">NORTHERN MARIANA ISLANDS</option>
        <option value="NO">NORWAY</option>
        <option value="OM">OMAN</option>
        <option value="PK">PAKISTAN</option>
        <option value="PW">PALAU</option>
        <option value="PA">PANAMA</option>
        <option value="PG">PAPUA NEW GUINEA</option>
        <option value="PY">PARAGUAY</option>
        <option value="PE">PERU</option>
        <option value="PH">PHILIPPINES</option>
        <option value="PN">PITCAIRN</option>
        <option value="PL">POLAND</option>
        <option value="PT">PORTUGAL</option>
        <option value="PR">PUERTO RICO</option>
        <option value="QA">QATAR</option>
        <option value="RE">REUNION</option>
        <option value="RO">ROMANIA</option>
        <option selected value="RU">RUSSIAN FEDERATION</option>
        <option value="RW">RWANDA</option>
        <option value="SH">SAINT HELENA</option>
        <option value="KN">SAINT KITTS AND NEVIS</option>
        <option value="LC">SAINT LUCIA</option>
        <option value="PM">SAINT PIERRE AND MIQUELON</option>
        <option value="VC">SAINT VINCENT AND THE GRENADINES</option>
        <option value="WS">SAMOA</option>
        <option value="SM">SAN MARINO</option>
        <option value="ST">SAO TOME AND PRINCIPE</option>
        <option value="SA">SAUDI ARABIA</option>
        <option value="SN">SENEGAL</option>
        <option value="CS">SERBIA AND MONTENEGRO</option>
        <option value="SC">SEYCHELLES</option>
        <option value="SL">SIERRA LEONE</option>
        <option value="SG">SINGAPORE</option>
        <option value="SK">SLOVAKIA</option>
        <option value="SI">SLOVENIA</option>
        <option value="SB">SOLOMON ISLANDS</option>
        <option value="SO">SOMALIA</option>
        <option value="ZA">SOUTH AFRICA</option>
        <option value="GS">SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS</option>
        <option value="ES">SPAIN</option>
        <option value="LK">SRI LANKA</option>
        <option value="SD">SUDAN</option>
        <option value="SR">SURINAME</option>
        <option value="SJ">SVALBARD AND JAN MAYEN ISLANDS</option>
        <option value="SZ">SWAZILAND</option>
        <option value="SE">SWEDEN</option>
        <option value="CH">SWITZERLAND</option>
        <option value="SY">SYRIAN ARAB REPUBLIC</option>
        <option value="TW">TAIWAN</option>
        <option value="TJ">TAJIKISTAN</option>
        <option value="TH">THAILAND</option>
        <option value="TL">TIMOR-LESTE</option>
        <option value="TG">TOGO</option>
        <option value="TK">TOKELAU</option>
        <option value="TO">TONGA</option>
        <option value="TT">TRINIDAD AND TOBAGO</option>
        <option value="TN">TUNISIA</option>
        <option value="TR">TURKEY</option>
        <option value="TM">TURKMENISTAN</option>
        <option value="TC">TURKS AND CAICOS ISLANDS</option>
        <option value="TV">TUVALU</option>
        <option value="UG">UGANDA</option>
        <option value="UA">UKRAINE</option>
        <option value="AE">UNITED ARAB EMIRATES</option>
        <option value="GB">UNITED KINGDOM</option>
        <option value="US">UNITED STATES</option>
        <option value="UM">UNITED STATES MINOR OUTLYING ISLANDS</option>
        <option value="UY">URUGUAY</option>
        <option value="UZ">UZBEKISTAN</option>
        <option value="VU">VANUATU</option>
        <option value="VE">VENEZUELA</option>
        <option value="VN">VIET NAM</option>
        <option value="WF">WALLIS AND FUTUNA ISLANDS</option>
        <option value="EH">WESTERN SAHARA</option>
        <option value="YE">YEMEN</option>
        <option value="ZM">ZAMBIA</option>
        <option value="ZW">ZIMBABWE</option>
    </select>
</template>

<style scoped>

</style>
<!--<option value="AALAND ISLANDS">AALAND ISLANDS</option>-->
<!--<option value="AFGHANISTAN">AFGHANISTAN</option>-->
<!--<option value="ALBANIA">ALBANIA</option>-->
<!--<option value="ALGERIA">ALGERIA</option>-->
<!--<option value="AMERICAN SAMOA">AMERICAN SAMOA</option>-->
<!--<option value="ANDORRA">ANDORRA</option>-->
<!--<option value="ANGOLA">ANGOLA</option>-->
<!--<option value="ANGUILLA">ANGUILLA</option>-->
<!--<option value="ANTARCTICA">ANTARCTICA</option>-->
<!--<option value="ANTIGUA AND BARBUDA">ANTIGUA AND BARBUDA</option>-->
<!--<option value="ARGENTINA">ARGENTINA</option>-->
<!--<option value="ARMENIA">ARMENIA</option>-->
<!--<option value="ARUBA">ARUBA</option>-->
<!--<option value="AUSTRALIA">AUSTRALIA</option>-->
<!--<option value="AUSTRIA">AUSTRIA</option>-->
<!--<option value="AZERBAIJAN">AZERBAIJAN</option>-->
<!--<option value="BAHAMAS">BAHAMAS</option>-->
<!--<option value="BAHRAIN">BAHRAIN</option>-->
<!--<option value="BANGLADESH">BANGLADESH</option>-->
<!--<option value="BARBADOS">BARBADOS</option>-->
<!--<option value="BELARUS">BELARUS</option>-->
<!--<option value="BELGIUM">BELGIUM</option>-->
<!--<option value="BELIZE">BELIZE</option>-->
<!--<option value="BENIN">BENIN</option>-->
<!--<option value="BERMUDA">BERMUDA</option>-->
<!--<option value="BHUTAN">BHUTAN</option>-->
<!--<option value="BOLIVIA">BOLIVIA</option>-->
<!--<option value="BOSNIA AND HERZEGOWINA">BOSNIA AND HERZEGOWINA</option>-->
<!--<option value="BOTSWANA">BOTSWANA</option>-->
<!--<option value="BOUVET ISLAND">BOUVET ISLAND</option>-->
<!--<option value="BRAZIL">BRAZIL</option>-->
<!--<option value="BRITISH INDIAN OCEAN TERRITORY">BRITISH INDIAN OCEAN TERRITORY</option>-->
<!--<option value="BRUNEI DARUSSALAM">BRUNEI DARUSSALAM</option>-->
<!--<option value="BULGARIA">BULGARIA</option>-->
<!--<option value="BURKINA FASO">BURKINA FASO</option>-->
<!--<option value="BURUNDI">BURUNDI</option>-->
<!--<option value="CAMBODIA">CAMBODIA</option>-->
<!--<option value="CAMEROON">CAMEROON</option>-->
<!--<option value="CANADA">CANADA</option>-->
<!--<option value="CAPE VERDE">CAPE VERDE</option>-->
<!--<option value="CAYMAN ISLANDS">CAYMAN ISLANDS</option>-->
<!--<option value="CENTRAL AFRICAN REPUBLIC">CENTRAL AFRICAN REPUBLIC</option>-->
<!--<option value="CHAD">CHAD</option>-->
<!--<option value="CHILE">CHILE</option>-->
<!--<option value="CHINA">CHINA</option>-->
<!--<option value="CHRISTMAS ISLAND">CHRISTMAS ISLAND</option>-->
<!--<option value="COLOMBIA">COLOMBIA</option>-->
<!--<option value="COMOROS">COMOROS</option>-->
<!--<option value="COOK ISLANDS">COOK ISLANDS</option>-->
<!--<option value="COSTA RICA">COSTA RICA</option>-->
<!--<option value="COTE D'IVOIRE">COTE D'IVOIRE</option>-->
<!--<option value="CUBA">CUBA</option>-->
<!--<option value="CYPRUS">CYPRUS</option>-->
<!--<option value="CZECH REPUBLIC">CZECH REPUBLIC</option>-->
<!--<option value="DENMARK">DENMARK</option>-->
<!--<option value="DJIBOUTI">DJIBOUTI</option>-->
<!--<option value="DOMINICA">DOMINICA</option>-->
<!--<option value="DOMINICAN REPUBLIC">DOMINICAN REPUBLIC</option>-->
<!--<option value="ECUADOR">ECUADOR</option>-->
<!--<option value="EGYPT">EGYPT</option>-->
<!--<option value="EL SALVADOR">EL SALVADOR</option>-->
<!--<option value="EQUATORIAL GUINEA">EQUATORIAL GUINEA</option>-->
<!--<option value="ERITREA">ERITREA</option>-->
<!--<option value="ESTONIA">ESTONIA</option>-->
<!--<option value="ETHIOPIA">ETHIOPIA</option>-->
<!--<option value="FAROE ISLANDS">FAROE ISLANDS</option>-->
<!--<option value="FIJI">FIJI</option>-->
<!--<option value="FINLAND">FINLAND</option>-->
<!--<option value="FRANCE">FRANCE</option>-->
<!--<option value="FRENCH GUIANA">FRENCH GUIANA</option>-->
<!--<option value="FRENCH POLYNESIA">FRENCH POLYNESIA</option>-->
<!--<option value="FRENCH SOUTHERN TERRITORIES">FRENCH SOUTHERN TERRITORIES</option>-->
<!--<option value="GABON">GABON</option>-->
<!--<option value="GAMBIA">GAMBIA</option>-->
<!--<option value="GEORGIA">GEORGIA</option>-->
<!--<option value="GERMANY">GERMANY</option>-->
<!--<option value="GHANA">GHANA</option>-->
<!--<option value="GIBRALTAR">GIBRALTAR</option>-->
<!--<option value="GREECE">GREECE</option>-->
<!--<option value="GREENLAND">GREENLAND</option>-->
<!--<option value="GRENADA">GRENADA</option>-->
<!--<option value="GUADELOUPE">GUADELOUPE</option>-->
<!--<option value="GUAM">GUAM</option>-->
<!--<option value="GUATEMALA">GUATEMALA</option>-->
<!--<option value="GUINEA">GUINEA</option>-->
<!--<option value="GUINEA-BISSAU">GUINEA-BISSAU</option>-->
<!--<option value="GUYANA">GUYANA</option>-->
<!--<option value="HAITI">HAITI</option>-->
<!--<option value="HEARD AND MC DONALD ISLANDS">HEARD AND MC DONALD ISLANDS</option>-->
<!--<option value="HONDURAS">HONDURAS</option>-->
<!--<option value="HONG KONG">HONG KONG</option>-->
<!--<option value="HUNGARY">HUNGARY</option>-->
<!--<option value="ICELAND">ICELAND</option>-->
<!--<option value="INDIA">INDIA</option>-->
<!--<option value="INDONESIA">INDONESIA</option>-->
<!--<option value="IRAQ">IRAQ</option>-->
<!--<option value="IRELAND">IRELAND</option>-->
<!--<option value="ISRAEL">ISRAEL</option>-->
<!--<option value="ITALY">ITALY</option>-->
<!--<option value="JAMAICA">JAMAICA</option>-->
<!--<option value="JAPAN">JAPAN</option>-->
<!--<option value="JORDAN">JORDAN</option>-->
<!--<option value="KAZAKHSTAN">KAZAKHSTAN</option>-->
<!--<option value="KENYA">KENYA</option>-->
<!--<option value="KIRIBATI">KIRIBATI</option>-->
<!--<option value="KUWAIT">KUWAIT</option>-->
<!--<option value="KYRGYZSTAN">KYRGYZSTAN</option>-->
<!--<option value="LAO PEOPLE'S DEMOCRATIC REPUBLIC">LAO PEOPLE'S DEMOCRATIC REPUBLIC</option>-->
<!--<option value="LATVIA">LATVIA</option>-->
<!--<option value="LEBANON">LEBANON</option>-->
<!--<option value="LESOTHO">LESOTHO</option>-->
<!--<option value="LIBERIA">LIBERIA</option>-->
<!--<option value="LIBYAN ARAB JAMAHIRIYA">LIBYAN ARAB JAMAHIRIYA</option>-->
<!--<option value="LIECHTENSTEIN">LIECHTENSTEIN</option>-->
<!--<option value="LITHUANIA">LITHUANIA</option>-->
<!--<option value="LUXEMBOURG">LUXEMBOURG</option>-->
<!--<option value="MACAU">MACAU</option>-->
<!--<option value="MADAGASCAR">MADAGASCAR</option>-->
<!--<option value="MALAWI">MALAWI</option>-->
<!--<option value="MALAYSIA">MALAYSIA</option>-->
<!--<option value="MALDIVES">MALDIVES</option>-->
<!--<option value="MALI">MALI</option>-->
<!--<option value="MALTA">MALTA</option>-->
<!--<option value="MARSHALL ISLANDS">MARSHALL ISLANDS</option>-->
<!--<option value="MARTINIQUE">MARTINIQUE</option>-->
<!--<option value="MAURITANIA">MAURITANIA</option>-->
<!--<option value="MAURITIUS">MAURITIUS</option>-->
<!--<option value="MAYOTTE">MAYOTTE</option>-->
<!--<option value="MEXICO">MEXICO</option>-->
<!--<option value="MONACO">MONACO</option>-->
<!--<option value="MONGOLIA">MONGOLIA</option>-->
<!--<option value="MONTSERRAT">MONTSERRAT</option>-->
<!--<option value="MOROCCO">MOROCCO</option>-->
<!--<option value="MOZAMBIQUE">MOZAMBIQUE</option>-->
<!--<option value="MYANMAR">MYANMAR</option>-->
<!--<option value="NAMIBIA">NAMIBIA</option>-->
<!--<option value="NAURU">NAURU</option>-->
<!--<option value="NEPAL">NEPAL</option>-->
<!--<option value="NETHERLANDS">NETHERLANDS</option>-->
<!--<option value="NETHERLANDS ANTILLES">NETHERLANDS ANTILLES</option>-->
<!--<option value="NEW CALEDONIA">NEW CALEDONIA</option>-->
<!--<option value="NEW ZEALAND">NEW ZEALAND</option>-->
<!--<option value="NICARAGUA">NICARAGUA</option>-->
<!--<option value="NIGER">NIGER</option>-->
<!--<option value="NIGERIA">NIGERIA</option>-->
<!--<option value="NIUE">NIUE</option>-->
<!--<option value="NORFOLK ISLAND">NORFOLK ISLAND</option>-->
<!--<option value="NORTHERN MARIANA ISLANDS">NORTHERN MARIANA ISLANDS</option>-->
<!--<option value="NORWAY">NORWAY</option>-->
<!--<option value="OMAN">OMAN</option>-->
<!--<option value="PAKISTAN">PAKISTAN</option>-->
<!--<option value="PALAU">PALAU</option>-->
<!--<option value="PANAMA">PANAMA</option>-->
<!--<option value="PAPUA NEW GUINEA">PAPUA NEW GUINEA</option>-->
<!--<option value="PARAGUAY">PARAGUAY</option>-->
<!--<option value="PERU">PERU</option>-->
<!--<option value="PHILIPPINES">PHILIPPINES</option>-->
<!--<option value="PITCAIRN">PITCAIRN</option>-->
<!--<option value="POLAND">POLAND</option>-->
<!--<option value="PORTUGAL">PORTUGAL</option>-->
<!--<option value="PUERTO RICO">PUERTO RICO</option>-->
<!--<option value="QATAR">QATAR</option>-->
<!--<option value="REUNION">REUNION</option>-->
<!--<option value="ROMANIA">ROMANIA</option>-->
<!--<option value="RUSSIAN FEDERATION" selected>RUSSIAN FEDERATION</option>-->
<!--<option value="RWANDA">RWANDA</option>-->
<!--<option value="SAINT HELENA">SAINT HELENA</option>-->
<!--<option value="SAINT KITTS AND NEVIS">SAINT KITTS AND NEVIS</option>-->
<!--<option value="SAINT LUCIA">SAINT LUCIA</option>-->
<!--<option value="SAINT PIERRE AND MIQUELON">SAINT PIERRE AND MIQUELON</option>-->
<!--<option value="SAINT VINCENT AND THE GRENADINES">SAINT VINCENT AND THE GRENADINES</option>-->
<!--<option value="SAMOA">SAMOA</option>-->
<!--<option value="SAN MARINO">SAN MARINO</option>-->
<!--<option value="SAO TOME AND PRINCIPE">SAO TOME AND PRINCIPE</option>-->
<!--<option value="SAUDI ARABIA">SAUDI ARABIA</option>-->
<!--<option value="SENEGAL">SENEGAL</option>-->
<!--<option value="SERBIA AND MONTENEGRO">SERBIA AND MONTENEGRO</option>-->
<!--<option value="SEYCHELLES">SEYCHELLES</option>-->
<!--<option value="SIERRA LEONE">SIERRA LEONE</option>-->
<!--<option value="SINGAPORE">SINGAPORE</option>-->
<!--<option value="SLOVAKIA">SLOVAKIA</option>-->
<!--<option value="SLOVENIA">SLOVENIA</option>-->
<!--<option value="SOLOMON ISLANDS">SOLOMON ISLANDS</option>-->
<!--<option value="SOMALIA">SOMALIA</option>-->
<!--<option value="SOUTH AFRICA">SOUTH AFRICA</option>-->
<!--<option value="SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS">SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS</option>-->
<!--<option value="SPAIN">SPAIN</option>-->
<!--<option value="SRI LANKA">SRI LANKA</option>-->
<!--<option value="SUDAN">SUDAN</option>-->
<!--<option value="SURINAME">SURINAME</option>-->
<!--<option value="SVALBARD AND JAN MAYEN ISLANDS">SVALBARD AND JAN MAYEN ISLANDS</option>-->
<!--<option value="SWAZILAND">SWAZILAND</option>-->
<!--<option value="SWEDEN">SWEDEN</option>-->
<!--<option value="SWITZERLAND">SWITZERLAND</option>-->
<!--<option value="SYRIAN ARAB REPUBLIC">SYRIAN ARAB REPUBLIC</option>-->
<!--<option value="TAIWAN">TAIWAN</option>-->
<!--<option value="TAJIKISTAN">TAJIKISTAN</option>-->
<!--<option value="THAILAND">THAILAND</option>-->
<!--<option value="TIMOR-LESTE">TIMOR-LESTE</option>-->
<!--<option value="TOGO">TOGO</option>-->
<!--<option value="TOKELAU">TOKELAU</option>-->
<!--<option value="TONGA">TONGA</option>-->
<!--<option value="TRINIDAD AND TOBAGO">TRINIDAD AND TOBAGO</option>-->
<!--<option value="TUNISIA">TUNISIA</option>-->
<!--<option value="TURKEY">TURKEY</option>-->
<!--<option value="TURKMENISTAN">TURKMENISTAN</option>-->
<!--<option value="TURKS AND CAICOS ISLANDS">TURKS AND CAICOS ISLANDS</option>-->
<!--<option value="TUVALU">TUVALU</option>-->
<!--<option value="UGANDA">UGANDA</option>-->
<!--<option value="UKRAINE">UKRAINE</option>-->
<!--<option value="UNITED ARAB EMIRATES">UNITED ARAB EMIRATES</option>-->
<!--<option value="UNITED KINGDOM">UNITED KINGDOM</option>-->
<!--<option value="UNITED STATES">UNITED STATES</option>-->
<!--<option value="UNITED STATES MINOR OUTLYING ISLANDS">UNITED STATES MINOR OUTLYING ISLANDS</option>-->
<!--<option value="URUGUAY">URUGUAY</option>-->
<!--<option value="UZBEKISTAN">UZBEKISTAN</option>-->
<!--<option value="VANUATU">VANUATU</option>-->
<!--<option value="VENEZUELA">VENEZUELA</option>-->
<!--<option value="VIET NAM">VIET NAM</option>-->
<!--<option value="WALLIS AND FUTUNA ISLANDS">WALLIS AND FUTUNA ISLANDS</option>-->
<!--<option value="WESTERN SAHARA">WESTERN SAHARA</option>-->
<!--<option value="YEMEN">YEMEN</option>-->
<!--<option value="ZAMBIA">ZAMBIA</option>-->
<!--<option value="ZIMBABWE">ZIMBABWE</option>-->